### PR TITLE
Added bundling for Node.js, browser, and ES6 modules

### PR DESCRIPTION
**Pull request by TomerAberbach**
This pull request addresses #23 and #24.

I switched the bundling from [webpack.js](https://webpack.js.org) to [rollup.js](https://rollupjs.org/guide/en) because I couldn't find anyway to accomplish what I needed using [webpack.js](https://webpack.js.org), and I usually use [rollup.js](https://rollupjs.org/guide/en) for my bundling anyway.

`yarn bundle` now generates:
1. An ES5 Node.js bundle: `sequency.node.js` and `sequency.node.min.js`.
2. An ES5 browser bundle: `sequency.browser.js` and `sequency.browser.min.js`.
3. An ES6 module bundle: `sequency.mjs` and `sequency.min.mjs`. This bundle can be used by both Node.js and the browser (which is why it doesn't generate two ES6 module bundles for Node.js and browser).

Each of these bundles is specified like so in `package.json`:
```json
{
  "main": "lib/sequency.node.min.js",
  "browser": "lib/sequency.browser.min.js",
  "module": "lib/sequency.min.mjs"
}
```

You can read about the `browser` field [here](https://docs.npmjs.com/files/package.json#browser) and the `module` field [here](https://rollupjs.org/guide/en#compatibility).

Let me know if you have any questions!

### CODE REVIEW

**Comment by winterbe** [comment]
Thanks for your contribution. I also tried to migrate to rollup in the past. I’ll look into your PR soon, probably next week.

**Comment by winterbe** [comment]
Just wanted to let you know that I'm too busy this week. Will look into your PR next week.

**Comment by jeremy-coleman** [comment]
i just did a few trials bundling several different ways, and comparing performance across each (and not breaking the lib).

The best option is to just use tsc -p --outDir _temp to transpile it into a temp directory and the rollup config wont need any plugins

this is the only rollup config you need.

```js
//import {terser} from 'rollup-plugin-terser'
var pkgJson = require('./package.json')
var devDeps = Object.keys(pkgJson.devDependencies || {})
var peerDeps = Object.keys(pkgJson.peerDependencies || {})
var pkgDeps = Object.keys(pkgJson.dependencies || {})

var EXTERNALS = devDeps.concat(peerDeps).concat(pkgDeps)


export default {
    external: EXTERNALS,
    input: '__sequency/Sequence.js',
	output: [
		{file: '_sequency/sequency.js', format: "es", sourcemap: false},
	],
	plugins: [
		//terser
	],
}
```

just target es modules and at the bottom of the file change exports to module.exports manually for your node target.
```js
//export { sequenceOf, emptySequence, asSequence, createSequence, isSequence, extendSequence, generateSequence, range };

const Sequency = { sequenceOf, emptySequence, asSequence, createSequence, isSequence, extendSequence, generateSequence, range }
module.exports = Sequency
```

i usually manually run terser something along the lines of this will do the trick

```js
var Terser = require("terser");
var fs = require('fs')
var jetpack = require('fs-jetpack')

var TERSER_CONFIG = {
      
      compress: {
          passes: 10,
          dead_code: true,
          keep_infinity: true,
          ecma: 8,
          hoist_funs: true,
          reduce_funcs: false, // i think this will cause polymorphic expressions
          unsafe_math: true,
          unsafe_proto: true, //good for perf maybe? but way slow to bundle
          unsafe_undefined: true, // turns undefined into void 0 , should really be called ensure_safe_undefined
          unsafe_regexp: true,
          negate_iife: false,
          unsafe_arrows: true, //arrow fns run faster in v8
          pure_getters: true,
          hoist_vars: true,
          arguments: true,
          unsafe_methods: true,
          
          //keep_fnames: true //idk seems like you should

      },
      mangle:{
        //keep_fnames: true,
        module: true,
        //regex: /^_MIN_/
      },
      ecma: 8,
      module: true,
      //nameCache: {},
      toplevel: true,
      output:{
        ecma: 8,
        wrap_iife: true
      }
}

function getFileSize(filePath) {
  var size = fs.statSync(filePath).size;
  var i = Math.floor( Math.log(size) / Math.log(1024) );
  return ( size / Math.pow(1024, i) ).toFixed(2) * 1 + ' ' + ['B', 'KB', 'MB', 'GB', 'TB'][i];
}


async function runTerser(i,o){
  await jetpack.write(o, Terser.minify(jetpack.read(i), TERSER_CONFIG).code)
  console.log(getFileSize(o))
}

runTerser('./_sequency/sequency.js', './_sequency_min/sequency.js')

```

**Comment by jeremy-coleman** [comment]
image

array length of 10m

**Comment by winterbe** [comment]
@TomerAberbach I've started reviewing your PR. While I still need more time to review and test the generated bundles in my projects, here's a few general thoughts:

- Instead of using the `.mjs` file extension we should stick with the more conservative `.modules.js` naming to prevent possible [tooling problems](https://medium.com/passpill-project/files-with-mjs-extension-for-javascript-modules-ced195d7c84a).
- We should provide minified versions + sourcemaps for both the browser and also the modules bundle.
- I'm not sure if we actually need an ES5 Node bundle if newer Node versions also support ES6 modules (disclaimer: I'm not a Node developer). Instead we could just generate a UMD bundle to cover browsers, commonjs and AMD? If we drop UMD support this could be a breaking change, if someone's using AMD.

@jeremy-coleman Thanks for your input. Can you please further explain why your approach is superior (faster?) than the provided solution in this PR?

**Comment by jeremy-coleman** [comment]
sorry for this but here it is. To me, having a clean and usable pre-minified output format is important. It allows you to debug and spot things that you would otherwise never be able to find. 

notice at the bottom, I manually added the module.exports for node. (and would need to comment out the exports if actually publishing). thats the only difference required 

```js
class All {
    all(predicate) {
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            if (!predicate(item.value)) {
                return false;
            }
        }
        return true;
    }
}

class Any {
    any(predicate) {
        if (predicate == null) {
            return !this.iterator.next().done;
        }
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            if (predicate(item.value)) {
                return true;
            }
        }
        return false;
    }
}

class AsIterable {
    asIterable() {
        const iterator = this.iterator;
        return {
            [Symbol.iterator]() {
                return iterator;
            }
        };
    }
}

class Associate {
    associate(transform) {
        const result = new Map();
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            const pair = transform(item.value);
            result.set(pair[0], pair[1]);
        }
        return result;
    }
}

class AssociateBy {
    associateBy(keyOrSelector, valueTransform) {
        const selector = typeof keyOrSelector === "function"
            ? keyOrSelector
            : (value) => value[keyOrSelector];
        const result = new Map();
        const transform = valueTransform != null
            ? valueTransform
            : (value) => value;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            const key = selector(item.value);
            const value = transform(item.value);
            result.set(key, value);
        }
        return result;
    }
}

class Average {
    average() {
        let sum = 0;
        let count = 0;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            sum += item.value;
            count++;
        }
        return count === 0
            ? Number.NaN
            : sum / count;
    }
}

class Chunk {
    chunk(chunkSize) {
        if (chunkSize < 1) {
            throw new Error("chunkSize must be > 0 but is " + chunkSize);
        }
        const result = [];
        let index = 0;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            const chunkIndex = Math.floor(index / chunkSize);
            if (result[chunkIndex] == null) {
                result[chunkIndex] = [item.value];
            }
            else {
                result[chunkIndex].push(item.value);
            }
            index++;
        }
        return result;
    }
}

class Contains {
    contains(element) {
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            if (element === item.value) {
                return true;
            }
        }
        return false;
    }
}

class Count {
    count(predicate) {
        let num = 0;
        if (predicate == null) {
            for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
                num++;
            }
        }
        else {
            for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
                if (predicate(item.value)) {
                    num++;
                }
            }
        }
        return num;
    }
}

class DistinctIterator {
    constructor(iterator) {
        this.iterator = iterator;
        this.items = [];
    }
    next(value) {
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            if (this.items.indexOf(item.value) < 0) {
                this.items.push(item.value);
                return { done: false, value: item.value };
            }
        }
        return { done: true, value: undefined };
    }
}
class Distinct {
    distinct() {
        return createSequence(new DistinctIterator(this.iterator));
    }
}

class DistinctByIterator {
    constructor(iterator, selector) {
        this.iterator = iterator;
        this.selector = selector;
        this.keys = [];
    }
    next(value) {
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            const key = this.selector(item.value);
            if (this.keys.indexOf(key) < 0) {
                this.keys.push(key);
                return { done: false, value: item.value };
            }
        }
        return { done: true, value: undefined };
    }
}
class DistinctBy {
    distinctBy(selector) {
        return createSequence(new DistinctByIterator(this.iterator, selector));
    }
}

class Drop {
    drop(n) {
        return this.withIndex()
            .dropWhile(it => it.index < n)
            .map(it => it.value);
    }
}

class DropWhileIterator {
    constructor(iterator, predicate) {
        this.iterator = iterator;
        this.predicate = predicate;
        this.dropping = true;
    }
    next(value) {
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            if (!this.dropping) {
                return { done: false, value: item.value };
            }
            const result = this.predicate(item.value);
            if (!result) {
                this.dropping = false;
                return { done: false, value: item.value };
            }
        }
        return { done: true, value: undefined };
    }
}
class DropWhile {
    dropWhile(predicate) {
        return createSequence(new DropWhileIterator(this.iterator, predicate));
    }
}

class ElementAt {
    elementAt(index) {
        let i = 0;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            if (i === index) {
                return item.value;
            }
            i++;
        }
        throw new Error("Index out of bounds: " + index);
    }
}

class ElementAtOrElse {
    elementAtOrElse(index, defaultValue) {
        let i = 0;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            if (i === index) {
                return item.value;
            }
            i++;
        }
        return defaultValue(index);
    }
}

class ElementAtOrNull {
    elementAtOrNull(index) {
        let i = 0;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            if (i === index) {
                return item.value;
            }
            i++;
        }
        return null;
    }
}

class FilterIterator {
    constructor(predicate, iterator) {
        this.predicate = predicate;
        this.iterator = iterator;
    }
    next(value) {
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            if (this.predicate(item.value)) {
                return { done: false, value: item.value };
            }
        }
        return { done: true, value: undefined };
    }
}
class Filter {
    filter(predicate) {
        return createSequence(new FilterIterator(predicate, this.iterator));
    }
}

class FilterIndexed {
    filterIndexed(predicate) {
        return this.withIndex()
            .filter(it => predicate(it.index, it.value))
            .map(it => it.value);
    }
}

class FilterNot {
    filterNot(predicate) {
        return this.filter((value) => !predicate(value));
    }
}

class FilterNotNull {
    filterNotNull() {
        return this.filter(it => it !== null);
    }
}

class First {
    first(predicate) {
        if (predicate != null) {
            return this.filter(predicate).first();
        }
        const item = this.iterator.next();
        if (item.done) {
            throw new Error("No such element");
        }
        return item.value;
    }
}

class FirstOrNull {
    firstOrNull(predicate) {
        if (predicate != null) {
            return this.filter(predicate).firstOrNull();
        }
        const item = this.iterator.next();
        return item.done
            ? null
            : item.value;
    }
    find(predicate) {
        return this.firstOrNull(predicate);
    }
}

class FlatMapIterator {
    constructor(transform, iterator) {
        this.transform = transform;
        this.iterator = iterator;
    }
    next(value) {
        if (this.current != null) {
            const item = this.current.next();
            if (!item.done) {
                return item;
            }
        }
        const next = this.iterator.next();
        if (!next.done) {
            const sequence = this.transform(next.value);
            this.current = sequence.iterator;
            return this.next();
        }
        return { done: true, value: undefined };
    }
}
class FlatMap {
    flatMap(transform) {
        return createSequence(new FlatMapIterator(transform, this.iterator));
    }
}

class Flatten {
    flatten() {
        return this.flatMap(it => {
            if (isSequence(it)) {
                return it;
            }
            else {
                return asSequence(it);
            }
        });
    }
}

class Fold {
    fold(initial, operation) {
        let result = initial;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            result = operation(result, item.value);
        }
        return result;
    }
}

class FoldIndexed {
    foldIndexed(initial, operation) {
        let result = initial;
        let index = 0;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            result = operation(index, result, item.value);
            index++;
        }
        return result;
    }
}

class ForEach {
    forEach(action) {
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            action(item.value);
        }
    }
}

class ForEachIndexed {
    forEachIndexed(action) {
        this.withIndex()
            .forEach(it => action(it.index, it.value));
    }
}

class GroupBy {
    groupBy(keySelector) {
        const result = new Map();
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            const key = keySelector(item.value);
            const array = result.get(key);
            if (array == null) {
                result.set(key, [item.value]);
            }
            else {
                array.push(item.value);
            }
        }
        return result;
    }
}

class IndexOf {
    indexOf(element) {
        let index = 0;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            if (element === item.value) {
                return index;
            }
            index++;
        }
        return -1;
    }
}

class IndexOfFirst {
    indexOfFirst(predicate) {
        let index = 0;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            if (predicate(item.value)) {
                return index;
            }
            index++;
        }
        return -1;
    }
}

class IndexOfLast {
    indexOfLast(predicate) {
        let index = 0;
        let result = -1;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            if (predicate(item.value)) {
                result = index;
            }
            index++;
        }
        return result;
    }
}

const defaults = {
    value: "",
    separator: ", ",
    prefix: "",
    postfix: "",
    limit: -1,
    truncated: "...",
    transform: undefined
};
class JoinToString {
    joinToString(config = defaults) {
        const { value = defaults.value, separator = defaults.separator, prefix = defaults.prefix, postfix = defaults.postfix, limit = defaults.limit, truncated = defaults.truncated, transform = defaults.transform } = config;
        let result = `${value}${prefix}`;
        let count = 0;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            count++;
            if (count > 1) {
                result += separator;
            }
            if (limit < 0 || count <= limit) {
                result += transform != null
                    ? transform(item.value)
                    : String(item.value);
            }
            else {
                break;
            }
        }
        if (limit >= 0 && count > limit) {
            result += truncated;
        }
        result += postfix;
        return result;
    }
    joinTo(config = defaults) {
        return this.joinToString(config);
    }
}

class Last {
    last(predicate) {
        if (predicate != null) {
            return this.filter(predicate).last();
        }
        let result;
        let empty = true;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            result = item.value;
            empty = false;
        }
        if (empty) {
            throw new Error("No such element");
        }
        return result;
    }
}

class LastOrNull {
    lastOrNull(predicate) {
        if (predicate != null) {
            return this.filter(predicate).lastOrNull();
        }
        let result = null;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            result = item.value;
        }
        return result;
    }
    findLast(predicate) {
        return this.lastOrNull(predicate);
    }
}

class MapIterator {
    constructor(transform, iterator) {
        this.transform = transform;
        this.iterator = iterator;
    }
    next(value) {
        const item = this.iterator.next();
        return item.done
            ? { done: true, value: undefined }
            : { done: false, value: this.transform(item.value) };
    }
}
class Map$1 {
    map(transform) {
        return createSequence(new MapIterator(transform, this.iterator));
    }
}

class MapIndexed {
    mapIndexed(transform) {
        return this.withIndex()
            .map(it => transform(it.index, it.value));
    }
}

class MapNotNull {
    mapNotNull(transform) {
        return this.flatMap((value) => {
            const item = transform(value);
            return item !== null
                ? sequenceOf(item)
                : emptySequence();
        });
    }
}

class Max {
    max() {
        let result = null;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            if (result == null || item.value > result) {
                result = item.value;
            }
        }
        return result;
    }
}

class MaxBy {
    maxBy(selector) {
        let max = null;
        let maxSelected = null;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            const value = selector(item.value);
            if (maxSelected == null || value > maxSelected) {
                maxSelected = value;
                max = item.value;
            }
        }
        return max;
    }
}

class MaxWith {
    maxWith(compare) {
        let max = null;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            if (max == null || compare(item.value, max) > 0) {
                max = item.value;
            }
        }
        return max;
    }
}

class Merge {
    merge(other, selector, prependNewValues = false) {
        let mergeValues = isSequence(other)
            ? other.toArray()
            : asSequence(other).toArray();
        const leftValues = this.toArray();
        const result = leftValues.map(left => {
            const selected = selector(left);
            const right = asSequence(mergeValues)
                .find(it => selector(it) === selected);
            if (right != null) {
                mergeValues = mergeValues.filter(it => it !== right);
                return right;
            }
            else {
                return left;
            }
        });
        if (prependNewValues) {
            return asSequence([...mergeValues, ...result]);
        }
        else {
            return asSequence([...result, ...mergeValues]);
        }
    }
}

class Min {
    min() {
        let result = null;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            if (result == null || item.value < result) {
                result = item.value;
            }
        }
        return result;
    }
}

class MinBy {
    minBy(selector) {
        let min = null;
        let minSelected = null;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            const value = selector(item.value);
            if (minSelected == null || value < minSelected) {
                minSelected = value;
                min = item.value;
            }
        }
        return min;
    }
}

class Minus {
    minus(data) {
        if (isSequence(data)) {
            const array = data.toArray();
            return this.filter(it => array.indexOf(it) < 0);
        }
        else if (data instanceof Array) {
            return this.filter(it => data.indexOf(it) < 0);
        }
        else {
            return this.filter(it => it !== data);
        }
    }
}

class MinWith {
    minWith(compare) {
        let min = null;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            if (min == null || compare(item.value, min) < 0) {
                min = item.value;
            }
        }
        return min;
    }
}

class None {
    none(predicate) {
        if (predicate == null) {
            return this.iterator.next().done;
        }
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            if (predicate(item.value)) {
                return false;
            }
        }
        return true;
    }
}

class OnEach {
    onEach(action) {
        return this.map(it => {
            action(it);
            return it;
        });
    }
}

class Partition {
    partition(predicate) {
        const arrayTrue = [];
        const arrayFalse = [];
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            if (predicate(item.value)) {
                arrayTrue.push(item.value);
            }
            else {
                arrayFalse.push(item.value);
            }
        }
        return { "true": arrayTrue, "false": arrayFalse };
    }
}

class AppendIterator {
    constructor(first, second) {
        this.first = first;
        this.second = second;
    }
    next(value) {
        const item1 = this.first.next();
        if (!item1.done) {
            return { done: false, value: item1.value };
        }
        const item2 = this.second.next();
        if (!item2.done) {
            return { done: false, value: item2.value };
        }
        return { done: true, value: undefined };
    }
}
class Plus {
    plus(data) {
        if (isSequence(data)) {
            return createSequence(new AppendIterator(this.iterator, data.iterator));
        }
        else if (data instanceof Array) {
            const iterator = data[Symbol.iterator]();
            return createSequence(new AppendIterator(this.iterator, iterator));
        }
        else {
            const iterator = [data][Symbol.iterator]();
            return createSequence(new AppendIterator(this.iterator, iterator));
        }
    }
}

class Reduce {
    reduce(operation) {
        const first = this.iterator.next();
        if (first.done) {
            throw new Error("Cannot reduce empty sequence");
        }
        let result = first.value;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            result = operation(result, item.value);
        }
        return result;
    }
}

class ReduceIndexed {
    reduceIndexed(operation) {
        const first = this.iterator.next();
        if (first.done) {
            throw new Error("Cannot reduce empty sequence");
        }
        let index = 1;
        let result = first.value;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            result = operation(index, result, item.value);
            index++;
        }
        return result;
    }
}

class Reverse {
    reverse() {
        return this.withIndex()
            .sortedByDescending(it => it.index)
            .map(it => it.value);
    }
}

class Single {
    single(predicate) {
        if (predicate != null) {
            return this.filter(predicate).single();
        }
        const first = this.iterator.next();
        if (first.done) {
            throw new Error("No such element");
        }
        if (!this.iterator.next().done) {
            throw new Error("Expect single element");
        }
        return first.value;
    }
}

class SingleOrNull {
    singleOrNull(predicate) {
        if (predicate != null) {
            return this.filter(predicate).singleOrNull();
        }
        const first = this.iterator.next();
        if (first.done) {
            return null;
        }
        if (!this.iterator.next().done) {
            return null;
        }
        return first.value;
    }
}

function compare(comparison) {
    return Object.assign(comparison, {
        reversed() {
            return compare((a, b) => comparison(a, b) * -1);
        },
        then(nextComparison) {
            return compare((a, b) => {
                const result = comparison(a, b);
                return result !== 0
                    ? result
                    : nextComparison(a, b);
            });
        },
        thenDescending(nextComparison) {
            return this.then(compare(nextComparison)
                .reversed());
        },
        thenBy(keyOrSelector) {
            const selector = asSelector(keyOrSelector);
            return this.then((a, b) => naturalCompare(selector(a), selector(b)));
        },
        thenByDescending(keyOrSelector) {
            const selector = asSelector(keyOrSelector);
            return this.then(compare((a, b) => naturalCompare(selector(a), selector(b))).reversed());
        }
    });
}
function compareBy(keyOrSelector) {
    const selector = asSelector(keyOrSelector);
    return compare((a, b) => naturalCompare(selector(a), selector(b)));
}
function compareByDescending(keyOrSelector) {
    const selector = asSelector(keyOrSelector);
    return compare((a, b) => naturalCompare(selector(b), selector(a)));
}
function asSelector(keyOrSelector) {
    return typeof keyOrSelector === "function"
        ? keyOrSelector
        : (item) => item[keyOrSelector];
}
function naturalCompare(a, b) {
    return a < b ? -1 : a > b ? 1 : 0;
}
function naturalOrder() {
    return compare(naturalCompare);
}
function reverseOrder() {
    return compare(naturalCompare).reversed();
}
function nullsLast() {
    return compare((a, b) => a === null ? 1 : b === null ? -1 : 0);
}
function nullsFirst() {
    return compare((a, b) => a === null ? -1 : b === null ? 1 : 0);
}
function createComparatorFactory() {
    return {
        compare,
        compareBy,
        compareByDescending,
        naturalOrder,
        reverseOrder,
        nullsFirst,
        nullsLast
    };
}

class Sorted {
    sorted(composeComparator) {
        const result = [];
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            result.push(item.value);
        }
        if (composeComparator == null) {
            result.sort();
        }
        else {
            const factory = createComparatorFactory();
            const comparator = composeComparator(factory);
            result.sort(comparator);
        }
        const iterator = result[Symbol.iterator]();
        return createSequence(iterator);
    }
}

class SortedBy {
    sortedBy(selector) {
        return this.sorted(it => it.compareBy(selector));
    }
}

class SortedByDescending {
    sortedByDescending(selector) {
        return this.sorted(it => it.compareByDescending(selector));
    }
}

class SortedDescending {
    sortedDescending() {
        return this.sorted(it => it.reverseOrder());
    }
}

class SortedWith {
    sortedWith(comparison) {
        return this.sorted(it => it.compare(comparison));
    }
}

class Sum {
    sum() {
        let result = 0;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            result += item.value;
        }
        return result;
    }
}

class SumBy {
    sumBy(selector) {
        let result = 0;
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            result += selector(item.value);
        }
        return result;
    }
}

class Take {
    take(n) {
        return this.withIndex()
            .takeWhile(it => it.index < n)
            .map(it => it.value);
    }
}

class TakeWhileIterator {
    constructor(iterator, predicate) {
        this.iterator = iterator;
        this.predicate = predicate;
    }
    next(value) {
        const item = this.iterator.next();
        if (!item.done) {
            const result = this.predicate(item.value);
            if (result) {
                return { done: false, value: item.value };
            }
        }
        return { done: true, value: undefined };
    }
}
class TakeWhile {
    takeWhile(predicate) {
        return createSequence(new TakeWhileIterator(this.iterator, predicate));
    }
}

class ToArray {
    toArray(array) {
        const result = array || [];
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            result.push(item.value);
        }
        return result;
    }
    toList(array) {
        return this.toArray(array);
    }
}

class ToMap {
    toMap(map) {
        const result = map || new Map();
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            const pair = item.value;
            const key = pair[0];
            const value = pair[1];
            result.set(key, value);
        }
        return result;
    }
}

class ToSet {
    toSet(set) {
        const result = set || new Set();
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            result.add(item.value);
        }
        return result;
    }
}

class Unzip {
    unzip() {
        const array1 = [];
        const array2 = [];
        for (let item = this.iterator.next(); !item.done; item = this.iterator.next()) {
            const [first, second] = item.value;
            array1.push(first);
            array2.push(second);
        }
        return [array1, array2];
    }
}

class IndexIterator {
    constructor(iterator) {
        this.iterator = iterator;
        this.index = -1;
    }
    next(value) {
        const item = this.iterator.next();
        if (item.done) {
            return { done: true, value: undefined };
        }
        this.index++;
        return {
            done: false,
            value: {
                index: this.index,
                value: item.value
            }
        };
    }
}
class WithIndex {
    withIndex() {
        return createSequence(new IndexIterator(this.iterator));
    }
}

class ZipIterator {
    constructor(iterator1, iterator2) {
        this.iterator1 = iterator1;
        this.iterator2 = iterator2;
    }
    next(value) {
        const item1 = this.iterator1.next();
        const item2 = this.iterator2.next();
        if (item1.done || item2.done) {
            return { done: true, value: undefined };
        }
        else {
            return { done: false, value: [item1.value, item2.value] };
        }
    }
}
class Zip {
    zip(other) {
        return createSequence(new ZipIterator(this.iterator, other.iterator));
    }
}

class GeneratorIterator {
    constructor(nextFunction) {
        this.nextFunction = nextFunction;
    }
    next(value) {
        const nextItem = this.nextFunction();
        return {
            done: nextItem == null,
            value: nextItem
        };
    }
}

class GeneratorSeedIterator {
    constructor(seed, nextFunction) {
        this.seed = seed;
        this.nextFunction = nextFunction;
    }
    next(value) {
        if (this.prevItem == null) {
            this.prevItem = this.seed;
            return { done: false, value: this.seed };
        }
        const nextItem = this.nextFunction(this.prevItem);
        if (nextItem == null) {
            return { done: true, value: undefined };
        }
        this.prevItem = nextItem;
        return {
            done: false,
            value: nextItem
        };
    }
}

class SequenceImpl {
    constructor(iterator) {
        this.iterator = iterator;
    }
}
applyMixins(SequenceImpl, [All, Any, AsIterable, Associate, AssociateBy, Average, Chunk, Contains, Count, Distinct, DistinctBy, Drop,
    DropWhile, ElementAt, ElementAtOrElse, ElementAtOrNull, Filter, FilterIndexed, FilterNot, FilterNotNull, First, FirstOrNull, FlatMap, Flatten, Fold, FoldIndexed,
    ForEach, ForEachIndexed, GroupBy, IndexOf, IndexOfFirst, IndexOfLast, JoinToString, Last, LastOrNull, Map$1, MapIndexed, MapNotNull, Max, MaxBy, MaxWith, Merge, Min, MinBy,
    Minus, MinWith, None, OnEach, Partition, Plus, Reduce, ReduceIndexed, Reverse, Single, SingleOrNull, Sorted, SortedBy, SortedByDescending, SortedDescending, SortedWith,
    Sum, SumBy, Take, TakeWhile, ToArray, ToMap, ToSet, Unzip, WithIndex, Zip]);
function applyMixins(derivedCtor, baseCtors) {
    baseCtors.forEach(baseCtor => {
        Object.getOwnPropertyNames(baseCtor.prototype).forEach(name => {
            derivedCtor.prototype[name] = baseCtor.prototype[name];
        });
    });
}
function sequenceOf(...args) {
    return asSequence(args);
}
function emptySequence() {
    return asSequence([]);
}
function asSequence(iterable) {
    if (iterable === null) {
        throw new Error("Cannot create sequence for input: null");
    }
    if (iterable === undefined) {
        throw new Error("Cannot create sequence for input: undefined");
    }
    if (iterable[Symbol.iterator] == null) {
        throw new Error("Cannot create sequence for non-iterable input: " + iterable);
    }
    const iterator = iterable[Symbol.iterator]();
    return createSequence(iterator);
}
function createSequence(iterator) {
    return new SequenceImpl(iterator);
}
function isSequence(object) {
    return object instanceof SequenceImpl;
}
function extendSequence(mixin) {
    applyMixins(SequenceImpl, [mixin]);
}
function generateSequence(a, b) {
    if (typeof a === "function" && b == null) {
        return createSequence(new GeneratorIterator(a));
    }
    const seed = typeof a === "function" ? a() : a;
    return seed != null
        ? createSequence(new GeneratorSeedIterator(seed, b))
        : emptySequence();
}
function range(start, endInclusive, step = 1) {
    if (start > endInclusive) {
        throw new Error(`start [${start}] must be lower then endInclusive [${endInclusive}]`);
    }
    if (start === endInclusive) {
        return emptySequence();
    }
    let current = start;
    return generateSequence(() => {
        try {
            return current <= endInclusive
                ? current
                : undefined;
        }
        finally {
            current += step;
        }
    });
}


export { sequenceOf, emptySequence, asSequence, createSequence, isSequence, extendSequence, generateSequence, range };

const Sequency = { sequenceOf, emptySequence, asSequence, createSequence, isSequence, extendSequence, generateSequence, range };
module.exports = Sequency
```

**Comment by hastebrot** [comment]
Maybe some input. Sequency works very well with the current UMD builds on the Observable live-coding site (https://observablehq.com/).

Screenshot 2019-05-09 at 05 16 01

**Comment by hastebrot** [comment]
I'm in favor of replacing webpack with rollup. There is also [microbundle](https://github.com/developit/microbundle) that provides some defaults for rollup.

Screenshot 2019-05-09 at 05 35 24

**Pull request closed without merging**
